# Generated by Django 2.0.2 on 2018-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20180319_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='to_user_id',
            new_name='to_account_no',
        ),
    ]
