# Generated by Django 2.0.2 on 2018-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20180320_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
